-- Migration manual para instalações novas; revisar schema existente e fazer backup antes de executar.
-- Não é executada automaticamente pela aplicação.
CREATE TABLE IF NOT EXISTS public.descargas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barco TEXT NOT NULL CHECK (char_length(trim(barco)) > 0),
    proprietario TEXT NOT NULL CHECK (char_length(trim(proprietario)) > 0),
    data_hora TIMESTAMPTZ NOT NULL DEFAULT now(),
    status TEXT NOT NULL DEFAULT 'Em Andamento' CHECK (status IN ('Em Andamento','Concluída'))
);
CREATE TABLE IF NOT EXISTS public.pecas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_descarga BIGINT NOT NULL REFERENCES public.descargas(id) ON DELETE RESTRICT,
    numero_peca INTEGER NOT NULL CHECK (numero_peca > 0),
    peso_kg NUMERIC(10,2) NOT NULL CHECK (peso_kg >= 5 AND peso_kg <= 350),
    categoria TEXT NOT NULL,
    segundo_furo BOOLEAN NOT NULL DEFAULT FALSE,
    lombo BOOLEAN NOT NULL DEFAULT FALSE,
    destino TEXT NOT NULL DEFAULT 'Caminhão' CHECK (destino IN ('Caminhão','Fábrica')),
    data_registro TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_pecas_descarga_numero UNIQUE (id_descarga,numero_peca)
);
CREATE INDEX IF NOT EXISTS idx_descargas_status_data ON public.descargas(status,data_hora DESC);
CREATE INDEX IF NOT EXISTS idx_pecas_descarga_numero ON public.pecas(id_descarga,numero_peca);
CREATE INDEX IF NOT EXISTS idx_pecas_destino ON public.pecas(destino);
