-- Execute manualmente no SQL Editor do Supabase depois de revisar.
-- Esta migration não é executada automaticamente pela aplicação.
CREATE TABLE IF NOT EXISTS public.descargas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barco TEXT NOT NULL CHECK (char_length(trim(barco)) > 0),
    proprietario TEXT NOT NULL CHECK (char_length(trim(proprietario)) > 0),
    datahora TIMESTAMPTZ NOT NULL DEFAULT now(),
    status TEXT NOT NULL DEFAULT 'Em Andamento' CHECK (status IN ('Em Andamento','Concluída'))
);
CREATE TABLE IF NOT EXISTS public.pecas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iddescarga BIGINT NOT NULL REFERENCES public.descargas(id) ON DELETE RESTRICT,
    numeropeca INTEGER NOT NULL CHECK (numeropeca > 0),
    pesokg NUMERIC(10,2) NOT NULL CHECK (pesokg >= 5 AND pesokg <= 350),
    categoria TEXT NOT NULL,
    segundofuro BOOLEAN NOT NULL DEFAULT FALSE,
    lombo BOOLEAN NOT NULL DEFAULT FALSE,
    destino TEXT NOT NULL CHECK (destino IN ('Caminhão','Fábrica')),
    dataregistro TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_pecas_descarga_numero UNIQUE (iddescarga,numeropeca)
);
CREATE INDEX IF NOT EXISTS idx_descargas_status_data ON public.descargas(status,datahora DESC);
CREATE INDEX IF NOT EXISTS idx_pecas_descarga_numero ON public.pecas(iddescarga,numeropeca);
CREATE INDEX IF NOT EXISTS idx_pecas_destino ON public.pecas(destino);
